# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

[package]
title = "{{ extension_display_name }}"
version = "{{ version }}"  # Semantic Versionning is used: https://semver.org/
description = "The simplest python extension example. Use it as a starting point for your extensions."
category = "Messaging"  # How to categorize this in the Extension Manager
changelog = "docs/CHANGELOG.md"
icon = "data/icon.png"  # Icon to show in the Extension Manager
keywords = ["kit", "messaging", "extra"]  # Search keywords for the Extension Manager
preview_image = "data/preview.png"  # Preview to show in the Extension Manager
readme = "docs/README.md" # Path (relative to the root) or content of readme markdown file for UI
repository = "https://github.com/NVIDIA-Omniverse/kit-app-template"  # URL of the extension source repository


[dependencies]
"omni.kit.livestream.messaging" = {}
"omni.usd" = {}
"omni.kit.viewport.utility" = {}


[settings]


[[python.module]]  # Main python module this extension provides, it will be publicly available as "import omni.hello.world"
name = "{{ extension_name }}"


[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.md",
]


[[test]]
dependencies = [
    "omni.activity.ui",
    "omni.kit.mainwindow",
    "omni.kit.stage_templates",
    # "omni.kit.test_suite.helpers",
    "omni.kit.ui_test",
    "omni.kit.viewport.utility",
    "omni.kit.viewport.window",
]

args = [
    "--/app/fastShutdown=1",
    "--/app/file/ignoreUnsavedOnExit=true",
    "--/app/window/dpiScaleOverride=1.0",
    "--/app/window/height=720",
    "--/app/window/scaleToMonitor=false",
    "--/app/window/width=1280",
    "--/exts/omni.kit.viewport.window/startup/windowName=Viewport",
    "--no-window",
    "--reset-user"
]
