[package]
# Semantic Versionning is used: https://semver.org/
version = "1.0.0"

# The title and description fields are primarily for displaying extension info in UI
title = "Setup Extension for My App"
description = "an extensions that Setup my App"

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# URL of the extension source repository.
repository = "https://github.com/NVIDIA-Omniverse/kit-app-template"

# One of categories for UI.
category = "setup"

# Keywords for the extension
keywords = ["kit", "app", "setup"]

# Icon to show in the extension manager
icon = "data/icon.png"

# Preview to show in the extension manager
preview_image = "data/preview.png"

# Use omni.ui to build simple UI
[dependencies]
"omni.kit.quicklayout" = {}
"omni.kit.window.title" = {}

# Main python module this extension provides, it will be publicly available as "import omni.hello.world".
[[python.module]]
name = "my_name.my_app.setup"
