# -- Application templates --
[templates."kit_base_editor"]
class = "ApplicationTemplate"
name = "Kit Base Editor"
url = "."
subpath = "apps/kit_base_editor/kit_base_editor.kit"
variables.application_name = "my_company.my_editor"
variables.application_display_name = "My Editor"
variables.version = "0.1.0"

[[templates."kit_base_editor".applications]]
template = "omni_default_streaming"
type = "streaming"


[templates."omni_usd_composer"]
class = "ApplicationTemplate"
name = "USD Composer"
url = "."
subpath = "apps/usd_composer/omni.usd_composer.kit"
variables.application_name = "my_company.my_usd_composer"
variables.application_display_name = "My USD Composer"
variables.version = "0.1.0"

[[templates."omni_usd_composer".extensions]]
template = "omni_usd_composer_setup"
type = "setup"

[[templates."omni_usd_composer".applications]]
template = "omni_default_streaming"
type = "streaming"


[[templates."omni_usd_composer".applications]]
template = "ovc_streaming"
type = "ovc"


[templates."omni_usd_explorer"]
class = "ApplicationTemplate"
name = "USD Explorer"
url = "."
subpath = "apps/usd_explorer/omni.usd_explorer.kit"
variables.application_name = "my_company.my_usd_explorer"
variables.application_display_name = "My USD Explorer"
variables.version = "0.1.0"

[[templates."omni_usd_explorer".extensions]]
template = "omni_usd_explorer_setup"
type = "setup"

[[templates."omni_usd_explorer".applications]]
template = "omni_default_streaming"
type = "streaming"


[[templates."omni_usd_explorer".applications]]
template = "ovc_streaming"
type = "ovc"


[templates."omni_usd_viewer"]
class = "ApplicationTemplate"
name = "USD Viewer"
url = "."
subpath = "apps/usd_viewer/omni.usd_viewer.kit"
variables.application_name = "my_company.my_usd_viewer"
variables.application_display_name = "My USD Viewer"
variables.version = "0.1.0"

[[templates."omni_usd_viewer".extensions]]
template = "omni_usd_viewer_messaging"
type = "extra"

[[templates."omni_usd_viewer".extensions]]
template = "omni_usd_viewer_setup"
type = "setup"


[[templates."omni_usd_viewer".applications]]
template = "omni_gdn_streaming"
type = "gdn"

[[templates."omni_usd_viewer".applications]]
template = "omni_default_streaming"
type = "streaming"

[templates."kit_service"]
class = "ApplicationTemplate"
name = "Kit Service"
url = "."
subpath = "apps/kit_service/kit_service.kit"
variables.application_name = "my_company.my_service"
variables.application_display_name = "My Service"
variables.version = "0.1.0"

[[templates."kit_service".extensions]]
template = "kit_service_setup"
type = "setup"


# -- Application Layer templates --
[templates."omni_default_streaming"]
class = "ApplicationLayerTemplate"
name = "Default Streaming"
url = "."
subpath = "apps/streaming_configs/default_stream.kit"
variables.version = "0.1.0"


[templates."omni_gdn_streaming"]
class = "ApplicationLayerTemplate"
name = "GDN Streaming"
url = "."
subpath = "apps/streaming_configs/gdn_stream.kit"
variables.version = "0.1.0"


[templates."omni_ovc_streaming"]
class = "ApplicationLayerTemplate"
name = "Omniverse Cloud Streaming"
url = "."
subpath = "apps/streaming_configs/ovc_stream.kit"
variables.version = "0.1.0"


# -- Extension templates --
[templates."basic_python_extension"]
class = "ExtensionTemplate"
name = "Basic Python Extension"
url = "."
subpath = "extensions/basic_python/template"
variables.extension_name = "my_company.my_python_extension"
variables.extension_display_name = "My Python Extension"
variables.version = "0.1.0"


[templates."basic_cpp_extension"]
class = "ExtensionTemplate"
name = "Basic C++ Extension"
url = "."
subpath = "extensions/basic_cpp/template"
variables.extension_name = "my_company.my_cpp_extension"
variables.extension_display_name = "My C++ Extension"
variables.version = "0.1.0"


[templates."basic_python_ui_extension"]
class = "ExtensionTemplate"
name = "Python UI Extension"
url = "."
subpath = "extensions/python_ui/template"
variables.extension_name = "my_company.my_python_ui_extension"
variables.extension_display_name = "My Python UI Extension"
variables.version = "0.1.0"


[templates."kit_service_setup"]
class = "SetupExtensionTemplate"
name = "Service Setup"
url = "."
subpath = "extensions/service.setup/template"
variables.extension_name = "my_company.my_service_setup_extension"
variables.extension_display_name = "My Service Setup Extension"
variables.version = "0.1.0"


[templates."omni_usd_composer_setup"]
class = "SetupExtensionTemplate"
name = "Omni USD Composer Setup"
url = "."
subpath = "extensions/usd_composer.setup/template"
variables.extension_name = "my_company.my_usd_composer_setup_extension"
variables.extension_display_name = "My USD Composer Setup Extension"
variables.version = "0.1.0"


[templates."omni_usd_explorer_setup"]
class = "SetupExtensionTemplate"
name = "Omni USD Explorer Setup"
url = "."
subpath = "extensions/usd_explorer.setup/template"
variables.extension_name = "my_company.my_usd_explorer_setup_extension"
variables.extension_display_name = "My USD Explorer Setup Extension"
variables.version = "0.1.0"


[templates."omni_usd_viewer_setup"]
class = "SetupExtensionTemplate"
name = "Omni USD Viewer Setup"
url = "."
subpath = "extensions/usd_viewer.setup/template"
variables.extension_name = "my_company.my_usd_viewer_setup_extension"
variables.extension_display_name = "My USD Viewer Setup Extension"
variables.version = "0.1.0"


[templates."omni_usd_viewer_messaging"]
class = "SetupExtensionTemplate"
name = "Omni USD Viewer Messaging"
url = "."
subpath = "extensions/usd_viewer.messaging/template"
variables.extension_name = "my_company.my_usd_viewer_messaging_extension"
variables.extension_display_name = "My USD Viewer Messaging Extension"
variables.version = "0.1.0"
