name: Smoke Test Staging Branch

on:
  push:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Required System Libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y zlib1g-dev

      - name: Make Templates
        run: python .github/workflows/create_templates.py

      - name: Run Build
        run: ./repo.sh build

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Make Templates
        run: python .github/workflows/create_templates.py

      - name: Run Build
        run: ./repo.bat build


  # test:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, windows-latest]

  #   steps:
